sudo: required
services:
  - docker

before_install:
  - docker build -t owen2709/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true owen2709/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-937699517699"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "AWS_SECRET_KEY"